csk/urls.py
from django.urls import path
from csk.views import *
app_name='csk'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

mi/urls.py
from django.urls import path
from mi.views import *
app_name='mi'
urlpatterns=[
    path('virat/',virat,name='virat'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,mi

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('mi/',include('mi.urls')),
]

csk/models.py
from django.db import models

# Create your models here.

mi/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

mi/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>DHONI</h1>
        <a href="{% url 'mi:virat' %}">GO TO MI PAGE</a>
    </center>

</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center> <h1> VIRAT PAGE</h1>
        <a href="{% url 'csk:dhoni' %}">GO TO DHONI PAGE</a>
    </center>
</body>
</html>